services:
  - type: web
    name: clarifai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && PYTHONPATH=$PYTHONPATH:. uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  - type: web
    name: clarifai-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0