name: Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p backend/models
        mkdir -p backend/uploads
        
    - name: Prepare deployment package
      run: |
        cd backend
        chmod +x startup.sh
        zip -r ../deploy.zip ./*
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A02AADC81E2D4148BEC128D3E1423B99 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B0DE5BE0AA2436B8645FF2B3B9EBE5E }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA64C9CE0DBB44359EB571DBBD3E6A4F }}
        enable-AzPSSession: true

    - name: Stop Web App
      shell: pwsh
      run: |
        az webapp stop --name clarifai-api --resource-group clarifai-rg
        Start-Sleep -Seconds 30
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: 'clarifai-api'
        slot-name: 'Production'
        package: deploy.zip
        
        
    - name: Start Web App
      shell: pwsh
      run: |
        az webapp start --name clarifai-api --resource-group clarifai-rg